#version: "3.8" deprecated
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  webTests:
    image: vidly-frontend
    volumes:
      - ./frontend:/app
    command: npm test
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh
  apiTests:
    build: ./backend
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: npm test
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db


volumes:
  vidly: